// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {main} from '../models';

export function GetProcesses():Promise<Array<app.ProcessMetrics>>;

export function GetStats():Promise<main.SystemStats>;
